name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/tmp/ujwal-git"

    - name: SSH into EC2 and move files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo cp /tmp/ujwal-git/index.html /var/www/html/index.html
          sudo cp /tmp/ujwal-git/styles.css /var/www/html/styles.css
          sudo systemctl restart nginx
